/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as UnitRouteImport } from './routes/unit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitRoute = UnitRouteImport.update({
  id: '/unit',
  path: '/unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/unit': typeof UnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/unit': typeof UnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/tentang': typeof TentangRoute
  '/unit': typeof UnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontak' | '/tentang' | '/unit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontak' | '/tentang' | '/unit'
  id: '__root__' | '/' | '/kontak' | '/tentang' | '/unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontakRoute: typeof KontakRoute
  TentangRoute: typeof TentangRoute
  UnitRoute: typeof UnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit': {
      id: '/unit'
      path: '/unit'
      fullPath: '/unit'
      preLoaderRoute: typeof UnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontakRoute: KontakRoute,
  TentangRoute: TentangRoute,
  UnitRoute: UnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
